export const ROUTES = Object.freeze({
  ABOUT_US: 'about-us',
  CALLBACK: 'callback',
  CART: 'cart',
  CHART: 'chart',
  CHECKOUT: 'check-out',
  CONTACT: 'contact',
  CREATE_ACCOUNT: 'create-account',
  DELIVERY: 'delivery',
  HOME: '/',
  LOGIN: 'login',
  METAL: 'metal',
  NOT_FOUND: 'not-found',
  PUBLICATIONS: 'publication',
  PRODUCTS: 'products',
  PROFILE: 'profile',
  RATES: 'rates',
  STORING: 'storing',
  UNDER_CONSTRUCTION: 'under-construction',
});
